### ISSUE TITLE
Adding activation hotkeys to author.properties

### ISSUE THREAD

**Issue by brimwats** [petoncle/mousemaster#11]
I've been playing around with [author.properties](https://github.com/petoncle/mousemaster/blob/main/configuration/author.properties) and I've actually enjoyed it a bunch! I've been able to figure out most of how things work with two exceptions--

1. how can I add a new startup hotkey to this? `idle-mode.to.normal-mode=_{none | modifierkey} #rightctrl -rightctrl` -- I tried adding F23 in front of the _, in the {}'s and after the rctrls but no luck!
2. is it possible to run mousemaster with the cmd output hidden? I've tried a bunch of variations on this, like shortcuts or AHK but they all seem to quit the CMD window immediately (flashes and then ends)

**Comment by petoncle** [comment]
>1. how can I add a new startup hotkey to this? idle-mode.to.normal-mode=_{none | modifierkey} #rightctrl -rightctrl -- I tried adding F23 in front of the _, in the {}'s and after the rctrls but no luck!

You would like to start it with F23? Only the F1-F12 keys can be used in the config file but if you need F23 I'll fix that. You have 24 F keys from F1 to F24?

>2. is it possible to run mousemaster with the cmd output hidden?

I think you can hide the command line window with a .bat file containing:
```bat
cmd /c start "" /min mousemaster.exe --configuration-file=mousemaster.properties
```
(This is assuming you put the .bat file in the same folder as mousemaster.exe and mousemaster.properties.)

When I run this bat file, mousemaster starts and the command line window gets hidden. The only way to stop it is to kill the mousemaster.exe process either via the task manager or with Win+R:
```bat
taskkill /F /IM mousemaster.exe
```

**Comment by brimwats** [comment]
> 1. You would like to start it with F23? Only the F1-F12 keys can be used in the config file but if you need F23 I'll fix that. You have 24 F keys from F1 to F24?

Yes please! I'm planning on starting it with alt + f23 in Kinesis, turning it on with f23 or the already existing hotkey and then killing it with Ctrl f23

> 2. <CMD>

oh yes, that makes absolute sense!! thank you!!

**Comment by petoncle** [comment]
I've added the missing f13 to f24 keys: [v44](https://github.com/petoncle/mousemaster/releases/). I don't have these keys on my keyboard, let me know if that worked or not.

**Comment by brimwats** [comment]
It works! If someone else wants to use the AHK you can do it like this:

```

; Define Alt+F23 to run start.bat
!F23::
SetWorkingDir, C:\Users\bri\syncthing\pc\00. Program Settings\57. Mousemaster
Run, cmd /c start "" /min mousemaster.exe --configuration-file=mousemaster.properties
return

; Define Alt+Ctrl+F23 to kill mousemaster.exe
!^F23::
Run, taskkill /F /IM mousemaster.exe,, Hide
return
```

by the way if you want to use F13 to F24, highly recommend using something like this:

```
;  ┌────────────────┐
;  │ 1b. Capslock  │
;  └───────────────┘
; Stay off unless activated with Win+Caps
; Variable to keep track of CapsLock state
capsLockState := 0
; This block toggles CapsLock state only when Win+CapsLock is pressed
#Capslock::
    KeyWait, Capslock  ; SetCapsLockState may fail without this.
    capsLockState := !capsLockState  ; Toggle the state
    SetCapsLockState, % capsLockState ? "On" : "AlwaysOff"
return
; This block sends the Esc key when CapsLock is pressed standalone
Capslock::Esc

;  ┌─────────────────┐
;  │ 3b. ShareX  │
;  └────────────────┘
Capslock & F1::F13 ; ShareX Keyboard command to screenshot to clipboard (no save)
Capslock & F2::F14 ; ShareX Keyboard command to OCR
Capslock & F3::F15 ; ShareX Keyboard command to Capture to Image Edit
Capslock & F4::F16 ; ShareX Keyboard command to capture to downloads (save)
Capslock & F5::F17 ; ShareX Keyboard command to record
Capslock & F6::F18 ; ShareX Keyboard command to scroll capture
Capslock & F7::F19 ; 
;Capslock & F8::F20
;Capslock & F9::F21
;Capslock & F10::F22  
;Capslock & F11::F23 ; Activates MM Active mode,  alt starts MM.exe and alt + ctrl +f23 kills MM.exe 
;Capslock & F12::F24
```

I have a whole world of Capslocks commands but that's a different convo :)

**Comment by brimwats** [comment]
Whoops! It seems like I spoke too soon; it looks like I was able to use the F23 AHK command without even updating to MM v44. I did the actual update and now it seems like it crashes immediately regardless of the AHK trigger or if I double click or run via cmd. Let me investigate a bit more too!

**Comment by brimwats** [comment]
Here's the error! I know the `If you trust this command, run the following command instead:` is empty but it's empty in powershell too! CMD error follows

```
Suggestion [3,General]: The command "mousemaster.exe" was not found, but does exist in the current location.
PowerShell does not load commands from the current location by default (see ''Get-Help about_Command_Precedence'').

If you trust this command, run the following command instead:
PS C:\Users\bri\syncthing\pc\00. Program Settings\57. Mousemaster> dir

    Directory: C:\Users\bri\syncthing\pc\00. Program Settings\57. Mousemaster

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---          2024-03-09  2:52 AM          17593 author.properties
-a---          2024-11-18  9:55 AM           1458 mousemaster - Shortcut.lnk
-a---          2024-11-21  8:17 AM       41237554 mousemaster.exe
-a---          2024-11-18  3:59 AM          20756 mousemaster.properties
-a---          2024-08-08 11:33 AM          10728 mousemaster.properties.bak
-a---          2024-11-18  1:39 AM           9853 mousemaster2.properties
-a---          2024-08-08 11:13 AM          10541 neo-mousekeys.properties
-a---          2024-11-18  1:36 AM          10541 neo-mousekeys2.properties
-a---          2024-11-21  7:56 AM             72 start.bat

PS C:\Users\bri\syncthing\pc\00. Program Settings\57. Mousemaster> mousemaster.exe
mousemaster.exe: The term 'mousemaster.exe' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

Suggestion [3,General]: The command "mousemaster.exe" was not found, but does exist in the current location.
PowerShell does not load commands from the current location by default (see ''Get-Help about_Command_Precedence'').

If you trust this command, run the following command instead:
PS C:\Users\bri\syncthing\pc\00. Program Settings\57. Mousemaster> .\mousemaster.exe
2024-11-21T14:07:26.029-08:00 [main] INFO  mousemaster.WindowsPlatform - SetProcessDpiAwarenessContext returned true
2024-11-21T14:07:26.030-08:00 [main] INFO  mousemaster.WindowsPlatform - Keyboard and mouse hooks installed
2024-11-21T14:07:26.034-08:00 [main] INFO  mousemaster.Mousemaster - Loaded configuration file mousemaster.properties
Exception in thread "main" java.lang.ExceptionInInitializerError
        at mousemaster.WindowsPlatform.reset(WindowsPlatform.java:102)
        at mousemaster.Mousemaster.loadConfiguration(Mousemaster.java:125)
        at mousemaster.Mousemaster.<init>(Mousemaster.java:26)
        at mousemaster.MousemasterApplication.main(MousemasterApplication.java:49)
        at java.base@21.0.5/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)
Caused by: java.lang.IllegalStateException: Some keyboardLayoutIndependentKeys are not defined in WindowsVirtualKey
        at mousemaster.WindowsVirtualKey.<clinit>(WindowsVirtualKey.java:427)
        ... 5 more
2024-11-21T14:07:26.037-08:00 [Thread-1] INFO  mousemaster.WindowsPlatform - Keyboard and mouse hooks uninstalled true successfully
2024-11-21T14:07:26.037-08:00 [Thread-1] INFO  mousemaster.WindowsPlatform - Single instance mutex released
PS C:\Users\bri\syncthing\pc\00. Program Settings\57. Mousemaster>
```

CMD error:

```
C:\Users\bri>cd C:\Users\bri\syncthing\pc\00. Program Settings\57. Mousemaster

C:\Users\bri\syncthing\pc\00. Program Settings\57. Mousemaster>mousemaster.exe
2024-11-21T14:08:46.471-08:00 [main] INFO  mousemaster.WindowsPlatform - SetProcessDpiAwarenessContext returned true
2024-11-21T14:08:46.471-08:00 [main] INFO  mousemaster.WindowsPlatform - Keyboard and mouse hooks installed
2024-11-21T14:08:46.476-08:00 [main] INFO  mousemaster.Mousemaster - Loaded configuration file mousemaster.properties
Exception in thread "main" java.lang.ExceptionInInitializerError
        at mousemaster.WindowsPlatform.reset(WindowsPlatform.java:102)
        at mousemaster.Mousemaster.loadConfiguration(Mousemaster.java:125)
        at mousemaster.Mousemaster.<init>(Mousemaster.java:26)
        at mousemaster.MousemasterApplication.main(MousemasterApplication.java:49)
        at java.base@21.0.5/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)
Caused by: java.lang.IllegalStateException: Some keyboardLayoutIndependentKeys are not defined in WindowsVirtualKey
        at mousemaster.WindowsVirtualKey.<clinit>(WindowsVirtualKey.java:427)
        ... 5 more
2024-11-21T14:08:46.479-08:00 [Thread-1] INFO  mousemaster.WindowsPlatform - Keyboard and mouse hooks uninstalled true successfully
2024-11-21T14:08:46.479-08:00 [Thread-1] INFO  mousemaster.WindowsPlatform - Single instance mutex released
```

**Comment by petoncle** [comment]
Oops, my bad. It appears I did not even try to run the app after making that change. Fix is in the latest release: [v44](https://github.com/petoncle/mousemaster/releases/).

**Comment by brimwats** [comment]
oopsie!! thaks so much for this!
